### ISSUE TITLE
When selecting an option input fields don't appear

### ISSUE THREAD

**Issue by MatejMecka** [wetalkit/legal-calculator#21]
Issue: Site is not usable.

Version: Chrome Mobile 61.0.3163 - Android 6.0.1
Tested also on Firefox Mobile 57.0 - Android 6.0.1 and it worked

![image](https://user-images.githubusercontent.com/24255804/32056443-fd68f492-ba64-11e7-86d6-11207f77ae01.png)

**Comment by TsTrv** [comment]
@MatejMecka Did the issue get fixed? Feel free to re-open if not.

**Comment by MatejMecka** [comment]
I checked now. The issue doesn't appear anymore. Maybe an update to Chrome or the project but I cannot reproduce it
